# Generated by Django 4.1.7 on 2023-03-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Satellite",
            fields=[
                ("RasterFileName", models.CharField(max_length=200)),
                (
                    "RasterFilePath",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                ("ImageFileName", models.CharField(max_length=200)),
                ("ImageFileBlob", models.TextField(blank=True)),
                ("Date", models.DateField()),
                ("TopleftLat", models.FloatField(max_length=200)),
                ("TopleftLng", models.FloatField(max_length=200)),
                ("ToprightLat", models.FloatField(max_length=200)),
                ("ToprightLng", models.FloatField(max_length=200)),
                ("BottomleftLat", models.FloatField(max_length=200)),
                ("BottomleftLng", models.FloatField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "Stream_id",
                    models.AutoField(default=0, primary_key=True, serialize=False),
                ),
                ("Date", models.DateField()),
                ("Depth", models.IntegerField()),
                ("Site", models.CharField(max_length=500)),
                ("Plot", models.CharField(max_length=200)),
                ("Year", models.IntegerField()),
                ("Value", models.FloatField(max_length=200)),
            ],
            options={"unique_together": {("Date", "Depth", "Site")},},
        ),
    ]
